version: '3.3'
services:
  app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: bdmonguete
    
  mongo:
    image: mongo
    container_name: mongoPrueba
    restart: always
   
    ports:
      - 3310:27017
    

volumes:
  mongo-data:
    
